---
- name: Debian OS
  block:

  - name: Install nginx Debian
    ansible.builtin.apt:
      name:
        - nginx
      state: latest
      update_cache: yes

  when: ansible_os_family == "Debian"

- name: Redhat OS
  block:

  - name: Install nginx RedHat
    ansible.builtin.dnf:
      name:
        - nginx
      state: latest
      enabled: yes

  when: ansible_os_family == "RedHat"

- name: Template nginx config files
  ansible.builtin.template:
    src: "nginx/{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
  loop:
    - sites-available/phpsite

- name: Create a symbolic default link to /etc/nginx/sites-available/upstreams
  ansible.builtin.file:
    src: /etc/nginx/sites-available/phpsite
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
