---
- name: Restart Chrony Debian
  ansible.builtin.service:
    name: chrony
    state: restarted
    daemon_reload: yes

- name: Restart Chronyd RedHat
  ansible.builtin.service:
    name: chronyd
    state: restarted
    daemon_reload: yes

- name: Start php-fpm service
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted
    enabled: yes
