---
- name: Debian OS
  block:

  - name: Installing Chrony Debian
    ansible.builtin.apt:
      name:
        - chrony
      state: present
      update_cache: yes

  - name: Start Chrony Service Debian
    ansible.builtin.systemd:
      name: chrony
      state: started
      enabled: yes

  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow
    notify: Restart Chrony Debian

  when: ansible_os_family == "Debian"

- name: Redhat OS
  block:

  - name: Installing Chrony RedHat
    ansible.builtin.dnf:
      name:
        - chrony
      state: present

  - name: Start Chronyd Service RedHat
    ansible.builtin.systemd:
      name: chronyd
      state: started
      enabled: yes

  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow
    notify: Restart Chronyd RedHat

  when: ansible_os_family == "RedHat"
